<a href="https://colab.research.google.com/github/DavideFeliceMeschino/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSORS


*   A torch Tensor is a multidimensional matrix containing elements of a single data type.
*   Similar to NumPy Arrays, but full of fun things that make them work better on GPU's(vs regular CPU's).
*   default data type of float32.
*   More suitable for deep learning than numpy array.






In [1]:
import torch
import numpy as np

LIST

In [3]:
my_list = [[1,2,3,4],[4,6,7,8]]
my_list

[[1, 2, 3, 4], [4, 6, 7, 8]]

NUMPY ARRAY

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.08668048, 0.49189583, 0.42640161, 0.08701421],
       [0.96207408, 0.88170448, 0.00559609, 0.27238594],
       [0.5140334 , 0.82812096, 0.61759288, 0.42212   ]])

In [5]:
np1.dtype

dtype('float64')

TENSORS

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-0.3870,  0.5291,  1.1033, -0.6856],
        [ 0.7009, -0.3441,  2.2117, -1.6129],
        [-0.0454, -1.7292,  0.2023,  0.8473]])

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## Create Tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0867, 0.4919, 0.4264, 0.0870],
        [0.9621, 0.8817, 0.0056, 0.2724],
        [0.5140, 0.8281, 0.6176, 0.4221]], dtype=torch.float64)